[package]
name = "orchestrator_client"
version = "0.1.0"
authors = ["connorcarpenter <connorcarpenter@gmail.com>"]
workspace = "../../../.."
edition = "2021"
publish = false

[dependencies]
orchestrator_proto = { path = "../proto" }

http = { path = "../../../../crates/http" }

bevy_app = { version = "0.12.1", default-features=false }
bevy_ecs = { version = "0.12.1", default-features=false }