[package]
name = "asset_render"
version = "0.1.0"
edition = "2021"
workspace = "../../.."

[features]

[dependencies]
asset_loader = { path = "../loader" }
render_api = { path = "../../render/render_api" }
storage = { path = "../../storage" }
ui_runner_config = { path = "../../ui/runner/config" }
logging = { path = "../../logging" }