[package]
name = "http_client"
version = "0.1.0"
edition = "2021"
workspace = "../../.."

[dependencies]
http_common = { path = "../http_common" }

naia-serde = { path = "../../../../naia/shared/serde" }

cfg-if = { version = "1.0" }
futures-lite = { version = "1.11.3" }
ehttp = { version = "0.3.0", features = ["native-async"] }