[package]
name = "egui_gl"
version = "0.23.0"
edition = "2021"
workspace = "../../.."

[features]

[dependencies]
gl = { path = "../gl" }

egui = { version = "0.22", default-features = false, features = [
  "bytemuck",
] }
bytemuck = { version = "1.7" }
log = { version = "0.4", features = ["std"] }
memoffset = { version = "0.6" }

# Web:
[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = { version = "0.3", features = ["console"] }
wasm-bindgen = { version = "0.2" }
