[package]
name = "world_server_naia_proto"
version = "0.1.0"
authors = ["connorcarpenter <connorcarpenter@gmail.com>"]
workspace = "../../.."
edition = "2021"
publish = false

[features]
local = []
prod = []

[dependencies]
naia-bevy-shared = { path = "../../../../naia/adapters/bevy/shared" }
crypto = { path = "../../../crates/crypto" }
asset_id = { path = "../../../crates/asset/id" }
logging = { path = "../../../crates/logging" }
random = { path = "../../../crates/random" }
math = { path = "../../../crates/math" }

bevy_ecs = { version = "0.14", default-features=false }

cfg-if = { version = "1.0" }