[package]
name = "ui_types"
version = "0.1.0"
edition = "2021"
workspace = "../../.."

[features]

[dependencies]
asset_id = { path = "../../asset/id" }
ui_layout = { path = "../layout" }
render_api = { path = "../../render/render_api" }