[package]
name = "standalone_native_deploy"
version = "0.1.0"
authors = ["connorcarpenter <connorcarpenter@gmail.com>"]
workspace = "../.."
edition = "2021"
publish = false

[[bin]]
name = "standalone"
path = "src/main.rs"

[features]
local = [ "launcher_app/local" ]
prod = [ "launcher_app/prod" ]
gl_renderer = [ "launcher_app/gl_renderer" ]
wgpu_renderer = [ "launcher_app/wgpu_renderer" ]

[dependencies]
# should only be kernel & apps here
kernel = { path = "../../crates/kernel" }
launcher_app = { path = "../../apps/launcher" }
game_app = { path = "../../apps/game" }
logging = { path = "../../crates/logging" }

# others
cfg-if = { version = "1.0" }