[package]
name = "email"
version = "0.1.0"
edition = "2021"
workspace = "../.."

[dependencies]
logging = { path = "../logging" }

lettre = { version = "0.10", features = ["builder", "tokio1-native-tls"] }
