[workspace]
resolver = "2"
# all crates should be listed here
members = [
    "apps/temp_2d",
    "apps/game/client",
    "apps/game/proto",
    "apps/game/server",
    "apps/vortex/client",
    "apps/vortex/proto",
    "apps/vortex/server",
    "crates/render_api",
    "crates/render_glow",
    "crates/render_egui",
    "crates/math",
]
# any crates with conflicting dependencies / feature flags cannot be put here
default-members = [

]

[profile.release]
opt-level = 's'
lto = true

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 1