[workspace]
resolver = "2"
# all crates should be listed here
members = [
    "apps/game/client",
    "apps/game/proto",
    "apps/game/server",
    "apps/editor/client",
    "apps/editor/proto",
    "apps/editor/server",
    "crates/render_api",
    "crates/render_glow",
    "crates/render_egui",
    "crates/math",
]
# any crates with conflicting dependencies / feature flags cannot be put here
default-members = [

]

[profile.release]
opt-level = 's'
lto = true