[workspace]
resolver = "2"
# all crates should be listed here
members = [
    "nexus/client",
    "nexus/proto",
    "nexus/server",
]
# any crates with conflicting dependencies / feature flags cannot be put here
default-members = [

]

[profile.release]
opt-level = 's'
lto = true