[workspace]
resolver = "2"
# all crates should be listed here
members = [
    "apps/game/client",
    "apps/game/engine",
    "apps/game/orchestrator",
    "apps/game/region",
    "apps/game/world/proto",
    "apps/game/world",
    "apps/game/session/proto",
    "apps/game/session",
    "apps/editor/client",
    "apps/editor/server/proto",
    "apps/editor/server",
    "crates/render_api",
    "crates/render_gl",
    "crates/render_egui",
    "crates/math",
    "crates/input",
    "crates/filetypes",
    "crates/asset",
    "crates/gl",
    "crates/egui_gl",
]
# any crates with conflicting dependencies / feature flags cannot be put here
default-members = [

]

[profile.release]
opt-level = 's'
lto = true

[profile.dev]
opt-level = 1
debug-assertions = false

[profile.dev.package."*"]
opt-level = 1