[package]
name = "render_api"
version = "0.1.0"
workspace = "../../.."
edition = "2021"
publish = false

[features]

[dependencies]
# Internal Crates
# THIS SHOULD *NEVER* include render_gl, render_wgpu, or render_egui
math = { path = "../../math" }
storage = { path = "../../storage" }

# External Crates
# should be very light on the number of dependencies
bevy_app = { version = "0.15", default-features=false }
bevy_ecs = { version = "0.15", default-features=false }

thiserror = "1"