[package]
name = "render_api"
version = "0.1.0"
workspace = "../../.."
edition = "2021"
publish = false

[features]

[dependencies]
# Internal Crates
# THIS SHOULD *NEVER* include render_gl, render_wgpu, or render_egui
math = { path = "../../math" }

# External Crates
# should be very light on the number of dependencies
bevy_app = { version = "0.12.1", default-features=false }
bevy_ecs = { version = "0.12.1", default-features=false }
bevy_log = { version = "0.12.1", default-features=false }
bevy_utils = { version = "0.12.1" }
thiserror = "1"