[package]
name = "input_gilrs"
version = "0.1.0"
edition = "2021"
workspace = "../../.."

[dependencies]
# should never include "render_gl" or "render_wgpu" here!

bevy_app = { version = "0.13", default-features = false }

