[package]
name = "ui_state"
version = "0.1.0"
edition = "2021"
workspace = "../../.."

[dependencies]
asset_id = { path = "../../asset/id" }
render_api = { path = "../../render/render_api" }
storage = { path = "../../storage" }
input = { path = "../../input" }
instant = { path = "../../instant" }
math = { path = "../../math" }

ui_layout = { path = "../layout" }
ui_types = { path = "../types" }

bevy_app = { version = "0.13", default-features = false }
bevy_ecs = { version = "0.13", default-features = false }
bevy_log = { version = "0.13", default-features=false }

# TODO: Remove this once Ui serialization is moved to `asset_serde` crate
serde = { version = "1.0.189", features = ["derive"] }
serde_json = { version = "1.0.107" }

unicode-segmentation = { version = "1.10.1" }