[package]
name = "input"
version = "0.1.0"
edition = "2021"
workspace = "../.."

[dependencies]
# should never include "render_gl" or "render_wgpu" here!

bevy_app = { version = "0.12.1", default-features = false }
bevy_ecs = { version = "0.12.1", default-features = false }
bevy_log = { version = "0.12.1", default-features = false }

math = { path = "../math" }
