[package]
name = "input"
version = "0.1.0"
edition = "2021"
workspace = "../.."

[dependencies]
# should never include "render_gl" or "render_wgpu" here!
input_winit = { path = "winit" }

bevy_app = { version = "0.13", default-features = false }

