[package]
name = "acme"
version = "0.1.0"
edition = "2021"
workspace = "../../.."

[features]
default = []

[dependencies]
rustls-acme = { version = "0.9" }
async-trait = { version = "0.1" }
base64 = { version = "0.22" }
blocking = { version = "1.5" }
ring = { version = "0.17", features = ["std"] }

acme_cert_db = { path = "cert_db" }