[package]
name = "acme"
version = "0.1.0"
edition = "2021"
workspace = "../../.."

[features]
default = []

[dependencies]
futures-rustls = { version = "0.25", default-features = false, features = ["ring"] }
futures = "0.3.21"
rcgen = { version = "0.12", default-features = false, features = ["pem", "ring"] }
serde_json = "1.0.81"
serde = { version = "1.0.137", features=["derive"] }
ring = { version = "0.17.7", features = ["std"] }
base64 = "0.21.7"
log = "0.4.17"
webpki-roots = "0.26"
pem = "3.0.3"
thiserror = "1.0.31"
x509-parser = "0.15.1"
chrono = { version = "0.4.24", default-features = false, features = ["clock"] }
async-trait = "0.1.53"
async-io = "2.3.0"
async-web-client = { version = "0.5.1", default-features = false }
http = "1"
blocking = "1.4.1"