[package]
name = "auth_server_types"
version = "0.1.0"
authors = ["connorcarpenter <connorcarpenter@gmail.com>"]
workspace = "../../.."
edition = "2021"
publish = false

[features]

[dependencies]
naia-serde = { path = "../../../../naia/shared/serde" }