[package]
name = "ui"
version = "0.1.0"
edition = "2021"
workspace = "../.."

[dependencies]
asset_id = { path = "../asset/asset_id" }
asset_render = { path = "../asset/render" }
render_api = { path = "../render/render_api" }
storage = { path = "../storage" }

bevy_app = { version = "0.13", default-features = false }
bevy_ecs = { version = "0.13", default-features = false }
bevy_log = { version = "0.13", default-features=false }

morphorm = { version = "0.6.4" }