[package]
name = "ui"
version = "0.1.0"
edition = "2021"
workspace = "../.."

[dependencies]
asset_id = { path = "../asset/asset_id" }
asset_render = { path = "../asset/render" }

bevy_app = { version = "0.13", default-features = false }
bevy_ecs = { version = "0.13", default-features = false }
bevy_log = { version = "0.13", default-features=false }
