[package]
name = "editor_proto"
version = "0.1.0"
authors = ["connorcarpenter <connorcarpenter@gmail.com>"]
workspace = "../../../.."
edition = "2021"
publish = false

[features]

[dependencies]
naia-bevy-shared = { path = "../../../../../naia/adapters/bevy/shared" }
math = { path = "../../../../crates/math" }
crypto = { path = "../../../../crates/crypto" }

bevy_ecs = { version = "0.13", default-features=false}
cfg-if = { version = "1.0" }
log = { version = "0.4" }

