[package]
name = "asset_id"
version = "0.1.0"
edition = "2021"
workspace = "../../.."

[features]

[dependencies]
crypto = { path = "../../crypto" }
naia-serde = { path = "../../../../naia/shared/serde" }