pub(crate) enum AuthServerError {
    EmailSendFailed(String),
    InsertedDuplicateUserId,
    UsernameAlreadyExists,
    EmailAlreadyExists,
    UsernameOrEmailNotFound,
    EmailNotFound,
    PasswordIncorrect,
    TokenNotFound,
    PasswordHashError,
    UsernameInvalidCharacters,
    EmailInvalidCharacters,
    PasswordInvalidCharacters,
    Unknown(String),
}
