[package]
name = "acme_cert_db"
version = "0.1.0"
authors = ["connorcarpenter <connorcarpenter@gmail.com>"]
workspace = "../../../.."
edition = "2021"
publish = false

[features]

[dependencies]
db = { path = "../../../db" }

serde = { version = "1.0.189", features = ["derive"] }