[package]
name = "render_gl"
version = "0.1.0"
workspace = "../../.."
edition = "2021"
publish = false

[features]

[dependencies]
# Internal Crates
# THIS SHOULD *NEVER* include render_wgpu
render_api = { path = "../render_api" }
math = { path = "../../math" }
input = { path = "../../input" }
gl = { path = "../gl" }
storage = { path = "../../storage" }

# External Crates
bevy_app = { version = "0.13", default-features = false }
bevy_ecs = { version = "0.13", default-features = false }
bevy_log = { version = "0.13", default-features = false }
bevy_utils = { version = "0.13", default-features = false }
cfg-if = { version = "1.0" }
thiserror = { version = "1" }
winit = { version = "0.29.10", default-features = false, features = ["rwh_05", "x11"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
glutin = { version = "0.31.3", default-features = false, features = ["glx", "x11"] }
raw-window-handle = { version = "0.5.2" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = { version = "0.2" }
serde = { version = "1", features = ["derive"] }
serde-wasm-bindgen = { version = "0.5" }
web-sys = { version = "0.3", features = ['Document', 'HtmlCollection', 'HtmlCanvasElement', 'Window'] }
instant = { version = "0.1.12" }
gloo-timers = { version = "0.3.0", features = ["futures"] }