[package]
name = "social_server_types"
version = "0.1.0"
authors = ["connorcarpenter <connorcarpenter@gmail.com>"]
workspace = "../../.."
edition = "2021"
publish = false

[features]

[dependencies]
naia-serde = { path = "../../../../naia/shared/serde" }
naia-bevy-shared = { path = "../../../../naia/adapters/bevy/shared" }

cfg-if = { version = "1.0" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
chrono = { version = "0.4" }