[package]
name = "render_glow"
version = "0.1.0"
workspace = "../.."
edition = "2021"
publish = false

[features]
editor = [ "render_egui", "getrandom" ]

[dependencies]
# Internal Crates
# THIS SHOULD *NEVER* include render_wgpu
render_api = { path = "../render_api" }
render_egui = { path = "../render_egui", optional = true }

# External Crates
bevy_app = { version = "0.10", default-features=false }
bevy_ecs = { version = "0.10", default-features=false }
bevy_log = { version = "0.10", default-features=false }
cfg-if = { version = "1.0" }
glow = "0.12"
cgmath = "0.18"
half = {version="2", features=["std", "num-traits", "zerocopy"]}
thiserror = "1"
winit = { version = "0.28" }
getrandom = { version = "0.2", features = ["js"], optional = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
glutin = { version = "0.30" }
raw-window-handle = { version = "0.5" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = {version = "0.2" }
serde = { version = "1", features = ["derive"] }
serde-wasm-bindgen = { version = "0.5" }
web-sys = { version = "0.3", features = ['Document', 'HtmlCollection', 'HtmlCanvasElement', 'Window'] }
instant = "0.1.12"