[package]
name = "asset_serde"
version = "0.1.0"
edition = "2021"
workspace = "../../.."

[features]
read_bits = [ "naia-serde", "ui_serde/read_bits", "spec_serde/read_bits" ]
write_bits = [ "naia-serde", "ui_serde/write_bits", "spec_serde/write_bits" ]
read_json = [ "serde", "serde_json", "ui_serde/read_json", "spec_serde/read_json" ]
write_json = [ "serde", "serde_json", "ui_serde/write_json", "spec_serde/write_json" ]

[dependencies]
cfg-if = { version = "1.0" }

asset_id = { path = "../id" }
ui_serde = { path = "../../ui/serde" }
spec_serde = { path = "../../spec/serde" }

# for BITS
naia-serde = { path = "../../../../naia/shared/serde", optional = true }

# for JSON
serde = { version = "1.0.189", features = ["derive"], optional = true }
serde_json = { version = "1.0.107", optional = true }