[package]
name = "cybl_game_client"
version = "0.1.0"
authors = ["connorcarpenter <connorcarpenter@gmail.com>"]
workspace = "../.."
edition = "2021"
publish = false

[features]
editor = []

[dependencies]
bevy_a11y = { version = "0.10", default-features=false }
bevy_app = { version = "0.10", default-features=false }
bevy_asset = { version = "0.10", default-features=false }
bevy_core = { version = "0.10", default-features=false }
bevy_core_pipeline = { version = "0.10", default-features=false, features = ["webgl"] }
bevy_ecs = { version = "0.10", default-features=false }
bevy_input = { version = "0.10", default-features=false }
bevy_log = { version = "0.10", default-features=false }
bevy_math = { version = "0.10", default-features=false }
bevy_pbr = { version = "0.10", default-features=false, features = ["webgl"] }
bevy_render = { version = "0.10", default-features=false, features = ["webgl"] }
bevy_sprite = { version = "0.10", default-features=false }
bevy_time = { version = "0.10", default-features=false }
bevy_transform = { version = "0.10", default-features=false }
bevy_winit = { version = "0.10", default-features=false, features = ["x11"] }
bevy_window = { version = "0.10", default-features=false }

cfg-if = { version = "1.0" }