[package]
name = "asset_loader"
version = "0.1.0"
edition = "2021"
workspace = "../../.."

[dependencies]
# should never include "render_gl" or "render_wgpu" here!
asset_serde = { path = "../serde", features = ["read_bits"] }
asset_id = { path = "../id" }
render_api = { path = "../../render/render_api" }
math = { path = "../../math" }
storage = { path = "../../storage" }
filesystem = { path = "../../filesystem" }
ui = { path = "../../ui" }
ui_types = { path = "../../ui/types" }
random = { path = "../../random" }
input = { path = "../../input" }
instant = { path = "../../instant" }

naia-serde = { path = "../../../../naia/shared/serde" }

bevy_app = { version = "0.13", default-features = false }
bevy_ecs = { version = "0.13", default-features = false }
bevy_log = { version = "0.13", default-features=false }