[package]
name = "http_server_shared"
version = "0.1.0"
edition = "2021"
workspace = "../../.."

[dependencies]
http_common = { path = "../http_common" }

once_cell = { version = "1.4.1" }
smol = { version = "1.3" }
async-dup = { version = "1.2.2" }
log = { version = "0.4" }