[package]
name = "http_server_shared"
version = "0.1.0"
edition = "2021"
workspace = "../../.."

[dependencies]
http_common = { path = "../http_common" }
executor = { path = "../../executor" }
logging = { path = "../../logging" }