[package]
name = "nexus_server"
version = "0.1.0"
authors = ["connorcarpenter <connorcarpenter@gmail.com>"]
workspace = "../.."
edition = "2021"
publish = false

[features]
editor = []

[dependencies]
nexus_proto = { path = "../proto" }
naia-bevy-server = { version = "0.20", features = [ "transport_webrtc" ] }

bevy_app = { version = "0.10", default-features=false }
bevy_ecs = { version = "0.10", default-features=false }
bevy_log = { version = "0.10", default-features=false }
