[package]
name = "editor_server"
version = "0.1.0"
authors = ["connorcarpenter <connorcarpenter@gmail.com>"]
workspace = "../../.."
edition = "2021"
publish = false

[features]

[dependencies]
editor_proto = { path = "proto" }
naia-bevy-server = { path = "../../../../naia/adapters/bevy/server", features = [ "transport_webrtc" ] }
asset_serde = { path = "../../../crates/asset/serde", features = ["read_json", "write_json"] }
asset_id = { path = "../../../crates/asset/id" }
math = { path = "../../../crates/math" }
crypto = { path = "../../../crates/crypto" }
logging = { path = "../../../crates/logging" }
git = { path = "../../../crates/git" }

# These are the official Bevy crates, going forward, we can use them because the Server isn't built for Wasm
bevy_app = { version = "0.14", default-features=false }
bevy_ecs = { version = "0.14", default-features=false }

# External crates
config_rs = { version ="0.14", package = "config", default-features = false, features = ["yaml"] }
serde = { version = "1.0", features = [ "derive" ] }

# TODO: remove this once loggin is updated the underlying tracing-log requirement from 0.1.2 to 0.2.0
regex = { version = "1.10.3", features = ["unicode-case"] }