[package]
name = "timequeue"
version = "0.1.0"
edition = "2021"
workspace = "../.."

[dependencies]
logging = { path = "../logging" }

naia-socket-shared = { path = "../../../naia/socket/shared", features = [ "wbindgen" ] }
