[package]
name = "orchestrator"
version = "0.1.0"
authors = ["connorcarpenter <connorcarpenter@gmail.com>"]
workspace = "../../.."
edition = "2021"
publish = false

[dependencies]
orchestrator_proto = { path = "proto" }
http_server = { path = "../../../crates/http_server" }
http_client = { path = "../../../crates/http_client" }
log = { version = "0.4", features = [] }
simple_logger = { version = "4.0", default-features = false, features = ["timestamps"] }