[package]
name = "orchestrator_proto"
version = "0.1.0"
authors = ["connorcarpenter <connorcarpenter@gmail.com>"]
workspace = "../../../.."
edition = "2021"
publish = false

[features]
client = [ "http" ]

[dependencies]
naia-serde = { path = "../../../../../naia/shared/serde" }
http = { path = "../../../../crates/bevy_http_client", optional = true }