[package]
name = "vortex_server"
version = "0.1.0"
authors = ["connorcarpenter <connorcarpenter@gmail.com>"]
workspace = "../../.."
edition = "2021"
publish = false

[features]

[dependencies]
vortex_proto = { path = "../proto" }
naia-bevy-server = { path = "../../../../naia/adapters/bevy/server", features = [ "transport_webrtc" ] }
filetypes = { path = "../../../crates/filetypes", features = ["read", "write"] }
math = { path = "../../../crates/math" }

# These are the official Bevy crates, going forward, we can use them because the Server isn't built for Wasm
bevy_app = { version = "0.11", default-features=false }
bevy_ecs = { version = "0.11", default-features=false }
bevy_log = { version = "0.11", default-features=false }

# External crates
git2 = { version = "0.17" }
config_rs = { version ="0.13", package = "config", default-features = false, features = ["yaml"] }
serde = { version = "1.0", features = [ "derive" ] }
