[tasks.install-target-wasm32-unknown-unknown]
command = "rustup"
args = ["target", "install", "wasm32-unknown-unknown"]

[tasks.install-wasm-bindgen-cli]
install_crate = { crate_name = "wasm-bindgen-cli", binary = "wasm-bindgen", test_arg="--help" }

# Dev

### Content Assets ###

# Content Remove Assets
[tasks.content-remove-assets]
command = "rm"
args = ["-r", "assets"]
dependencies = []

# Content Add Assets
[tasks.content-add-assets]
command = "mkdir"
args = ["assets"]
dependencies = ["content-remove-assets"]

### Game ###

# Game Cargo Build
[tasks.game-cargo-build]
command = "cargo"
args = [
    "build",
    "--manifest-path", "./../../deployments/web/game/Cargo.toml",
    "--target-dir", "./../../deployments/web/game/target",
    "--features", "gl_renderer,local",
    "--target", "wasm32-unknown-unknown",
    "--lib",
]
dependencies = ["content-add-assets", "install-target-wasm32-unknown-unknown"]

# Game Wasm-Bindgen
[tasks.game-wasm-bindgen]
command = "wasm-bindgen"
args = [
    "--out-dir", "assets",
    "--out-name", "game",
    "--target", "web",
    "--no-typescript",
    "./../../deployments/web/game/target/wasm32-unknown-unknown/debug/game.wasm"
]
dependencies = ["game-cargo-build", "install-wasm-bindgen-cli"]

# Game Copy HTML
[tasks.game-copy-html]
command = "cp"
args = [
    "./../../deployments/web/game/game.html",
    "assets/game.html"
]
dependencies = ["game-wasm-bindgen"]

### Launcher ###

# Launcher Cargo Build
[tasks.launcher-cargo-build]
command = "cargo"
args = [
    "build",
    "--manifest-path", "./../../deployments/web/launcher/Cargo.toml",
    "--target-dir", "./../../deployments/web/launcher/target",
    "--features", "gl_renderer,local",
    "--target", "wasm32-unknown-unknown",
    "--lib",
]
dependencies = ["content-add-assets", "install-target-wasm32-unknown-unknown"]

# Launcher Wasm-Bindgen
[tasks.launcher-wasm-bindgen]
command = "wasm-bindgen"
args = [
    "--out-dir", "assets",
    "--out-name", "launcher",
    "--target", "web",
    "--no-typescript",
    "./../../deployments/web/launcher/target/wasm32-unknown-unknown/debug/launcher.wasm"
]
dependencies = ["launcher-cargo-build", "install-wasm-bindgen-cli"]

# Launcher Copy HTML
[tasks.launcher-copy-html]
command = "cp"
args = [
    "./../../deployments/web/launcher/launcher.html",
    "assets/launcher.html"
]
dependencies = ["launcher-wasm-bindgen"]

### Serve ###
[tasks.serve]
command = "cargo"
args = ["run", "--features", "local"]
dependencies = ["game-copy-html", "launcher-copy-html"]

## Release
#
## Cargo Build
#[tasks.cargo-build-wasm-release]
#command = "cargo"
#args = ["build", "--release", "--features", "gl_renderer,local", "--target", "wasm32-unknown-unknown", "--lib", "--target-dir", "target"]
#dependencies = ["install-target-wasm32-unknown-unknown"]
#
## Wasm-Bindgen
#[tasks.wasm-bindgen-release]
#command = "wasm-bindgen"
#args = ["--out-dir", "target", "--out-name", "game", "--target", "web", "--no-typescript", "target/wasm32-unknown-unknown/release/game.wasm"]
#dependencies = ["cargo-build-wasm-release", "install-wasm-bindgen-cli"]
#
## Serve
#[tasks.serve-release]
#command = "basic-http-server"
#args = ["-x"]
#dependencies = ["wasm-bindgen-release", "install-basic-http-server"]





