[tasks.install-target-wasm32-unknown-unknown]
command = "rustup"
args = ["target", "install", "wasm32-unknown-unknown"]

[tasks.install-wasm-bindgen-cli]
install_crate = { crate_name = "wasm-bindgen-cli", binary = "wasm-bindgen", test_arg="--help" }

# Dev

### Content Files ###

# Content Remove Files
[tasks.content-remove-files]
command = "rm"
args = ["-r", "files"]
dependencies = []

# Content Add Files
[tasks.content-add-files]
command = "mkdir"
args = ["files"]
dependencies = ["content-remove-files"]

### Game ###

# Game Cargo Build
[tasks.game-cargo-build]
command = "cargo"
args = [
    "build",
    "--manifest-path", "./../../deployments/web/game/Cargo.toml",
    "--target-dir", "./../../deployments/web/game/target",
    "--features", "gl_renderer,local",
    "--target", "wasm32-unknown-unknown",
    "--lib",
]
dependencies = ["content-add-files", "install-target-wasm32-unknown-unknown"]

# Game Wasm-Bindgen
[tasks.game-wasm-bindgen]
command = "wasm-bindgen"
args = [
    "--out-dir", "files",
    "--out-name", "game",
    "--target", "web",
    "--no-typescript",
    "./../../deployments/web/game/target/wasm32-unknown-unknown/debug/game.wasm"
]
dependencies = ["game-cargo-build", "install-wasm-bindgen-cli"]

# Game Copy HTML
[tasks.game-copy-html]
command = "cp"
args = [
    "./../../deployments/web/game/game.html",
    "files/game.html"
]
dependencies = ["game-wasm-bindgen"]

### Launcher ###

# Launcher Cargo Build
[tasks.launcher-cargo-build]
command = "cargo"
args = [
    "build",
    "--manifest-path", "./../../deployments/web/launcher/Cargo.toml",
    "--target-dir", "./../../deployments/web/launcher/target",
    "--features", "gl_renderer,local",
    "--target", "wasm32-unknown-unknown",
    "--lib",
]
dependencies = ["content-add-files", "install-target-wasm32-unknown-unknown"]

# Launcher Wasm-Bindgen
[tasks.launcher-wasm-bindgen]
command = "wasm-bindgen"
args = [
    "--out-dir", "files",
    "--out-name", "launcher",
    "--target", "web",
    "--no-typescript",
    "./../../deployments/web/launcher/target/wasm32-unknown-unknown/debug/launcher.wasm"
]
dependencies = ["launcher-cargo-build", "install-wasm-bindgen-cli"]

# Launcher Copy HTML
[tasks.launcher-copy-html]
command = "cp"
args = [
    "./../../deployments/web/launcher/launcher.html",
    "files/launcher.html"
]
dependencies = ["launcher-wasm-bindgen"]

### Serve ###
[tasks.serve]
command = "cargo"
args = ["run", "--features", "local"]
dependencies = ["game-copy-html", "launcher-copy-html"]

### Release ###

### Game ###

# Game Cargo Build
[tasks.game-cargo-build-release]
command = "cargo"
args = [
    "build",
    "--release",
    "--manifest-path", "./../../deployments/web/game/Cargo.toml",
    "--target-dir", "./../../deployments/web/game/target",
    "--features", "gl_renderer,local",
    "--target", "wasm32-unknown-unknown",
    "--lib",
]
dependencies = ["content-add-files", "install-target-wasm32-unknown-unknown"]

# Game Wasm-Bindgen
[tasks.game-wasm-bindgen-release]
command = "wasm-bindgen"
args = [
    "--out-dir", "files",
    "--out-name", "game",
    "--target", "web",
    "--no-typescript",
    "./../../deployments/web/game/target/wasm32-unknown-unknown/release/game.wasm"
]
dependencies = ["game-cargo-build-release", "install-wasm-bindgen-cli"]

# Game Copy HTML
[tasks.game-copy-html-release]
command = "cp"
args = [
    "./../../deployments/web/game/game.html",
    "files/game.html"
]
dependencies = ["game-wasm-bindgen-release"]

### Launcher ###

# Launcher Cargo Build
[tasks.launcher-cargo-build-release]
command = "cargo"
args = [
    "build",
    "--release",
    "--manifest-path", "./../../deployments/web/launcher/Cargo.toml",
    "--target-dir", "./../../deployments/web/launcher/target",
    "--features", "gl_renderer,local",
    "--target", "wasm32-unknown-unknown",
    "--lib",
]
dependencies = ["content-add-files", "install-target-wasm32-unknown-unknown"]

# Launcher Wasm-Bindgen
[tasks.launcher-wasm-bindgen-release]
command = "wasm-bindgen"
args = [
    "--out-dir", "files",
    "--out-name", "launcher",
    "--target", "web",
    "--no-typescript",
    "./../../deployments/web/launcher/target/wasm32-unknown-unknown/release/launcher.wasm"
]
dependencies = ["launcher-cargo-build-release", "install-wasm-bindgen-cli"]

# Launcher Copy HTML
[tasks.launcher-copy-html-release]
command = "cp"
args = [
    "./../../deployments/web/launcher/launcher.html",
    "files/launcher.html"
]
dependencies = ["launcher-wasm-bindgen-release"]

### Serve ###
[tasks.serve-release]
command = "cargo"
args = ["run", "--features", "local"]
dependencies = ["game-copy-html-release", "launcher-copy-html-release"]