[package]
name = "http_server"
version = "0.1.0"
authors = ["connorcarpenter <connorcarpenter@gmail.com>"]
workspace = "../../.."
edition = "2021"
publish = false

[features]

[dependencies]
http_common = { path = "../http_common" }
http_server_shared = { path = "../http_server_shared" }

naia-serde = { path = "../../../../naia/shared/serde" }

smol = { version = "1.3" }
async-dup = { version = "1.2.2" }
log = { version = "0.4" }