[package]
name = "ui_render"
version = "0.1.0"
edition = "2021"
workspace = "../../.."

[features]

[dependencies]
asset_loader = { path = "../../asset/loader" }
asset_render = { path = "../../asset/render" }
render_api = { path = "../../render/render_api" }
storage = { path = "../../storage" }

ui_state = { path = "../../ui/state" }
ui_runtime = { path = "../../ui/runtime" }
ui_runtime_config = { path = "../../ui/runtime_config" }
ui_input = { path = "../../ui/input" }

bevy_log = { version = "0.13", default-features=false }