[package]
name = "ui_runtime_config"
version = "0.1.0"
edition = "2021"
workspace = "../../../.."

[features]

[dependencies]
render_api = { path = "../../../render/render_api" }
asset_id = { path = "../../../asset/id" }
math = { path = "../../../math" }

ui_layout = { path = "../../layout" }
ui_builder_config = { path = "../../builder/config" }
ui_serde = { path = "../../serde" }

bevy_app = { version = "0.13", default-features = false }
bevy_ecs = { version = "0.13", default-features = false }
bevy_log = { version = "0.13", default-features=false }