[package]
name = "vultr"
version = "0.1.0"
workspace = "../../.."
edition = "2021"

[dependencies]
reqwest = { version = "0.11.22", default-features = false, features = ["json"] }
serde = { version = "1.0.189", features = ["derive"] }
serde_json = { version = "1.0.107" }

[features]
default = ["nativetls"]
nativetls = ["reqwest/default-tls"]
blocking = ["reqwest/blocking"]

#rustls = ["reqwest/rustls-tls"]
#gzip = ["reqwest/gzip"]
#brotli = ["reqwest/brotli"]
#deflate = ["reqwest/deflate"]