[package]
name = "random"
version = "0.1.0"
edition = "2021"
workspace = "../.."

[dependencies]
rand = { version = "0.8.5" }
logging = { path = "../logging" }

naia-socket-shared = { path = "../../../naia/socket/shared", features = [ "wbindgen" ] }