[package]
name = "vortex_client"
version = "0.1.0"
authors = ["connorcarpenter <connorcarpenter@gmail.com>"]
workspace = "../../.."
edition = "2021"
publish = false

[[bin]]
name = "app"
path = "src/main.rs"

[lib]
name = "app"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
# Internal Crates
vortex_proto = { path = "../proto" }
math = { path = "../../../crates/math" }
render_api = { path = "../../../crates/render_api" }
render_gl = { path = "../../../crates/render_gl" }
render_egui = { path = "../../../crates/render_egui" }
input = { path = "../../../crates/input" }

# External Crates
naia-bevy-client = { path = "../../../../naia/adapters/bevy/client", features = ["transport_webrtc"] }
bevy_app = { version = "0.11", default-features=false }
bevy_ecs = { version = "0.11", default-features=false }
bevy_log = { version = "0.11", default-features=false }
cfg-if = { version = "1.0" }
egui-modal = { version = "0.2.2" }
config_rs = { version ="0.13", package = "config", default-features = false, features = ["yaml"] }
serde = { version = "1.0", features = [ "derive" ] }

# Wasm Only
[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = { version = "0.2.84", features = [ "serde-serialize" ] }