[package]
name = "asset_io"
version = "0.1.0"
edition = "2021"
workspace = "../../.."

[features]
read_bits = [ "naia-serde" ]
write_bits = [ "naia-serde" ]
read_json = [ "serde", "serde_json" ]
write_json = [ "serde", "serde_json" ]

[dependencies]
cfg-if = { version = "1.0" }
log = { version = "0.4" }

render_api = { path = "../../render/render_api" }
asset_id = { path = "../id" }
crypto = { path = "../../crypto" }
ui = { path = "../../ui" }

# for BITS
naia-serde = { path = "../../../../naia/shared/serde", optional = true }

# for JSON
serde = { version = "1.0.189", features = ["derive"], optional = true }
serde_json = { version = "1.0.107", optional = true }