[package]
name = "bevy_http_server"
version = "0.1.0"
edition = "2021"
workspace = "../../.."

[dependencies]
logging = { path = "../../../crates/logging" }
http_common = { path = "../http_common" }
bevy_http_shared = { path = "../bevy_http_shared" }
http_server_shared = { path = "../http_server_shared" }

naia-serde = { path = "../../../../naia/shared/serde" }

bevy_ecs = { version = "0.13", default-features = false }
bevy_app = { version = "0.13", default-features = false }

async-dup = { version = "1.2.2" }

cfg-if = { version = "1.0" }