[package]
name = "nexus_proto"
version = "0.1.0"
authors = ["connorcarpenter <connorcarpenter@gmail.com>"]
workspace = "../.."
edition = "2021"
publish = false

[features]
editor = []

[dependencies]
naia-bevy-shared = { version = "0.20" }

bevy_ecs = { version = "0.10", default-features=false}
cfg-if = { version = "1.0" }
log = { version = "0.4" }