[package]
name = "cybl_game_server"
version = "0.1.0"
authors = ["connorcarpenter <connorcarpenter@gmail.com>"]
workspace = "../.."
edition = "2021"
publish = false

[dependencies]
cybl_game_proto = { path = "../proto" }
naia-bevy-server = { version = "0.20", features = [ "transport_webrtc" ] }

bevy_app = { version = "0.10", default-features=false }
bevy_core = { version = "0.10", default-features=false }
bevy_ecs = { version = "0.10", default-features=false }
bevy_log = { version = "0.10", default-features=false }
