[package]
name = "bevy_http_client"
version = "0.1.0"
edition = "2021"
workspace = "../../.."

[dependencies]
http_common = { path = "../http_common" }
http_client_shared = { path = "../http_client_shared" }
naia-serde = { path = "../../../../naia/shared/serde" }

bevy_tasks = { version = "0.12.1", default-features = false, features = ["multi-threaded"] }
bevy_ecs = { version = "0.12.1", default-features = false }
bevy_app = { version = "0.12.1", default-features = false }
bevy_core = { version = "0.12.1", default-features = false }

cfg-if = { version = "1.0" }
log = "0.4.17"

[target.'cfg(target_arch = "wasm32")'.dependencies]
crossbeam-channel = "0.5.7"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
futures-lite = { version = "1.11.3" }