[package]
name = "bevy_http_client"
version = "0.1.0"
edition = "2021"
workspace = "../../.."

[dependencies]
http_common = { path = "../http_common" }
http_client_shared = { path = "../http_client_shared" }
naia-serde = { path = "../../../../naia/shared/serde" }
logging = { path = "../../../crates/logging" }
executor = { path = "../../../crates/executor" }

bevy_ecs = { version = "0.13", default-features = false }
bevy_app = { version = "0.13", default-features = false }
bevy_core = { version = "0.13", default-features = false }

cfg-if = { version = "1.0" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
crossbeam-channel = "0.5.7"