[package]
name = "ui_render"
version = "0.1.0"
edition = "2021"
workspace = "../../../.."

[features]

[dependencies]
asset_loader = { path = "../../../asset/loader" }
asset_render = { path = "../../../asset/render" }
render_api = { path = "../../../render/render_api" }
storage = { path = "../../../storage" }
logging = { path = "../../../logging" }
math = { path = "../../../math" }

ui_runner = { path = ".." }

bevy_app = { version = "0.15", default-features = false }
bevy_ecs = { version = "0.15", default-features = false }