[package]
name = "render_egui"
version = "0.1.0"
workspace = "../../.."
edition = "2021"
publish = false

[dependencies]
# Internal Crates
render_api = { path = "../render_api" }
render_gl = { path = "../render_gl" }
math = { path = "../../math" }
input = { path = "../../input" }
egui_gl = { path = "../egui_gl" }
storage = { path = "../../storage" }
logging = { path = "../../logging" }

# External Crates
bevy_app = { version = "0.15", default-features = false }
bevy_ecs = { version = "0.15", default-features = false }

egui = { version = "=0.22.0" }
# egui_extras = { version = "0.21.0" }
winit = { version = "0.28", default-features = false, features = ["x11"] }