[package]
name = "http_client_shared"
version = "0.1.0"
edition = "2021"
workspace = "../../.."

[dependencies]
http_common = { path = "../http_common" }

# For compiling natively:
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
ureq = "2.0"
async-channel = { version = "1.8" }

# For compiling to web:
[target.'cfg(target_arch = "wasm32")'.dependencies]
js-sys = "0.3"
wasm-bindgen = "0.2.87"
wasm-bindgen-futures = "0.4"

[dependencies.web-sys]
version = "0.3.52"
features = [
  "AbortSignal",
  "Headers",
  "ReadableStream",
  "Request",
  "RequestInit",
  "RequestMode",
  "Response",
  "Window",
]
