[package]
name = "http_client_shared"
version = "0.1.0"
edition = "2021"
workspace = "../../.."

[dependencies]
http_common = { path = "../http_common" }
log = "0.4.17"

# For compiling natively:
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
ureq = { version = "2.0" }
async-channel = { version = "2.2.0" }
async-net = { version = "1.4.3" }
url = { version = "2.2" }
futures-lite = { version = "2.0.1" }
executor = { path = "../../executor" }

# For compiling to web:
[target.'cfg(target_arch = "wasm32")'.dependencies]
js-sys = { version = "0.3" }
wasm-bindgen = { version = "0.2" }
wasm-bindgen-futures = { version ="0.4" }
web-sys = { version = "0.3", features = [ "AbortController", "AbortSignal", "Headers", "ReadableStream", "Request",
  "RequestInit", "RequestMode", "Response", "Window" ] }

