[package]
name = "neocontent_server"
version = "0.1.0"
authors = ["connorcarpenter <connorcarpenter@gmail.com>"]
workspace = "../.."
edition = "2021"
publish = false

[features]
local = [ "config/local", "automation_lib" ]
prod = [ "config/prod" ]

[dependencies]
http_server = { path = "../../crates/http/http_server" }
http_client = { path = "../../crates/http/http_client" }
config = { path = "../../config", features = ["content"] }
automation_lib = { path = "../../apps/automation/lib", optional = true }
asset_serde = { path = "../../crates/asset/serde", features = ["read_json"] }
asset_id = { path = "../../crates/asset/id" }
logging = { path = "../../crates/logging" }

neocontent_server_http_proto = { path = "http_proto" }

cfg-if = { version = "1.0" }