[package]
name = "ui_input"
version = "0.1.0"
edition = "2021"
workspace = "../../../.."

[dependencies]
input = { path = "../../../input" }
math = { path = "../../../math" }
instant = { path = "../../../instant" }
logging = { path = "../../../logging" }
asset_id = { path = "../../../asset/id" }
ui_state = { path = "../state" }
ui_runner_config = { path = "../config" }

bevy_ecs = { version = "0.13", default-features = false }

ascii = { version = "1.1.0" }