[package]
name = "ui_runner"
version = "0.1.0"
edition = "2021"
workspace = "../../.."

[features]

[dependencies]
asset_loader = { path = "../../asset/loader" }
clipboard = { path = "../../clipboard" }
storage = { path = "../../storage" }
render_api = { path = "../../render/render_api" }
asset_id = { path = "../../asset/id" }
input = { path = "../../input" }
math = { path = "../../math" }

ui_state = { path = "state" }
ui_input = { path = "input" }
ui_runner_config = { path = "config" }

bevy_app = { version = "0.13", default-features = false }
bevy_ecs = { version = "0.13", default-features = false }
bevy_log = { version = "0.13", default-features=false }