[package]
name = "math"
version = "0.1.0"
edition = "2021"
workspace = "../.."

[dependencies]
glam = { version = "0.23" }
naia-serde = { path = "../../../naia/shared/serde" }
random = { path = "../random" }
log = { version = "0.4" }

