[package]
name = "math"
version = "0.1.0"
edition = "2021"
workspace = "../.."

[dependencies]
logging = { path = "../logging" }

naia-serde = { path = "../../../naia/shared/serde" }

glam = { version = "0.23" }

