[package]
name = "game_web_deploy"
version = "0.1.0"
authors = ["connorcarpenter <connorcarpenter@gmail.com>"]
workspace = "../../../.."
edition = "2021"
publish = false

[lib]
name = "game"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[features]
local = [ "game_app/local", "config/local" ]
prod = [ "game_app/prod", "config/prod" ]
gl_renderer = [ "game_app/gl_renderer" ]
wgpu_renderer = [ "game_app/wgpu_renderer" ]

[dependencies]
kernel = { path = "../../../../crates/kernel" }
logging = { path = "../../../../crates/logging" }
game_app = { path = "../../../game", features = ["no_odst"] }
config = { path = "../../../../config", features = ["client"] }

cfg-if = { version = "1.0" }

wasm-bindgen = { version = "0.2", features = [ "serde-serialize" ] }
wasm-bindgen-futures = { version = "0.4.40" }